### PR TITLE
Att representation

### PR DESCRIPTION
**Pull request by drinkdhmo**

### CODE REVIEW

**Comment by plusk01** [comment]
@drinkdhmo is there a dependency I need to install? The widgets are showing up blank (see below).

euler-blank

**Comment by drinkdhmo** [comment]
Plotting cells must be run individually. This is probably an issue with the matplotlib notebook backend.

**Comment by drinkdhmo** [comment]
Running all works fine in Binder. Both plots show up and are interactive.

**Comment by drinkdhmo** [comment]
- [x] Need to add exp and log for matrices and quaternions

**Pull request merged**
