### PR TITLE
Quadcopter application

### PR DESCRIPTION
**Pull request by mjhaskell**
This branch contains an updated version of the presentation on the quadcopter application on SO(3). The updates include changing the cross-product syntax to be different than the hat operator as well as adding a visual diagram for the lie operators.

### CODE REVIEW

**Comment by plusk01** [comment]
@mhask94 it looks like you forgot to add the `files/Lie_operators_aid.png`. Can you do that? Thanks!

**Comment by mjhaskell** [comment]
@plusk01 from what I can tell, that image is inside the files directory on my branch. I thought I added that in the last commit (14bde0c). I'm not sure what to change for it to show up for you.

**Comment by plusk01** [comment]
Oh, my apologies -- I see it now.

I do have a nitpick for you, though. Instead of `[.]$_x$`, will you use `$[\cdot]_\times$`? Using `\times` instead of `x` looks better:

image

vs

image

**Comment by mjhaskell** [comment]
Thanks! I was trying to find a better way to show the dot in brackets, but I didn't know about \cdot. Those changes have been made, the document should use _\times instead of _x throughout.

**Pull request merged**
